"""test table

Revision ID: 4f16916192da
Revises: 0e8921ef4a23
Create Date: 2019-12-04 17:34:10.902037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f16916192da'
down_revision = '0e8921ef4a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_table_name'), ['name'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index('ix_task_name')

    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('complete IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index('ix_task_name', ['name'], unique=False)

    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_table_name'))

    op.drop_table('test_table')
    # ### end Alembic commands ###
