"""increased character limit on post table again

Revision ID: 609ea639f081
Revises: 773e761da55d
Create Date: 2019-12-05 21:50:04.665695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609ea639f081'
down_revision = '773e761da55d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
