"""increased character limit on post table

Revision ID: 773e761da55d
Revises: 9f66beda18d3
Create Date: 2019-12-05 21:44:45.105966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773e761da55d'
down_revision = '9f66beda18d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
