"""increased char limit on post table

Revision ID: 9f66beda18d3
Revises: 4f16916192da
Create Date: 2019-12-05 21:27:18.406541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f66beda18d3'
down_revision = '4f16916192da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.drop_index('ix_test_table_name')

    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_table', schema=None) as batch_op:
        batch_op.create_index('ix_test_table_name', ['name'], unique=False)

    # ### end Alembic commands ###
