"""update tasks

Revision ID: 9fd99f74749d
Revises: b66bd87e2b49
Create Date: 2019-12-04 14:32:59.403455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd99f74749d'
down_revision = 'b66bd87e2b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_of_task', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_name_of_task'), ['name_of_task'], unique=False)
        batch_op.drop_index('ix_task_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_task_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_task_name_of_task'))
        batch_op.drop_column('name_of_task')

    # ### end Alembic commands ###
